#!/usr/bin/env bash

# *** Add a user to linux or macos, depending on system *** #

if [[ "$(uname)" == "Darwin" ]]; then
  add_a_user() {
    USER=$1
    PASSWORD=$2
    shift
    shift
    COMMENTS=$*
    echo "Adding user $USER ..."
    echo sudo dscl . -create /Users/"$USER" Comment "$COMMENTS"
    echo sudo dscl . -passwd /Users/"$USER" "$PASSWORD"
    echo "Added user $USER ($COMMENTS) with pass $PASSWORD"
  }
elif [[ "$(uname)" == "Linux" ]]; then
  add_a_user() {
    USER=$1
    PASSWORD=$2
    shift
    shift
    # Having shifted twice, the rest is now comments ...
    COMMENTS=$*
    echo "Adding user $USER ..."
    echo useradd -c "$COMMENTS, $USER"
    echo passwd "$USER $PASSWORD"
    echo "Added user $USER ($COMMENTS) with pass $PASSWORD"
  }
fi
