#!/usr/local/bin/zsh

# Allows you to make .zsh_config files for any project directory, and then when you cd to that
# directory, zsh will read the .zsh_config file and use those settings

function chpwd() {
  if [ -r $PWD/.zsh_config ]; then
    source $PWD/.zsh_config
  else
    source $HOME/.zshrc
  fi
}

