#!/bin/bash

# Check if ~/.ssh/config file exists
if [ -f ~/.ssh/config ]; then
  # Backup existing config file
  cp ~/.ssh/config ~/.ssh/config_old
fi

# Generate a new SSH key for GitHub
printf "Generating a new SSH key for GitHub...\n"
ssh-keygen -t ed25519 -C "personal-github" -f "$HOME/.ssh/personal-github"

# Add SSH key to the ssh-agent
eval "$(ssh-agent -s)"

# Create or update the Configuration File
touch ~/.ssh/config
printf "Host *\n IgnoreUnknown UseKeychain\n AddKeysToAgent yes\n UseKeychain yes\n \n Host personal-github\n Hostname github.com\n User LukeAims\n IdentityFile ~/.ssh/personal-github" | tee ~/.ssh/config

# Add SSH key to keychain
ssh-add --apple-use-keychain ~/.ssh/personal-github

# Display instructions for adding the SSH key to GitHub
printf "Running 'pbcopy < ~/.ssh/personal-github.pub' now paste that into GitHub\n"
pbcopy < ~/.ssh/personal-github.pub