#!/usr/local/bin/zsh
# shellcheck disable=SC1071

printf "Generating a new SSH key for GitHub..."

# Generating a new SSH key
# https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key
ssh-keygen -t ed25519 -C "personal-github" -f "$HOME/.ssh/personal-github"

# Adding your SSH key to the ssh-agent
# https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent
eval "$(ssh-agent -s)"

# Create my Configuration File
touch ~/.ssh/config
printf "Host *\n IgnoreUnknown UseKeychain\n AddKeysToAgent yes\n UseKeychain yes\n \n Host personal-github\n Hostname github.com\n User LukeAims\n IdentityFile ~/.ssh/personal-github" | tee ~/.ssh/config

ssh-add --apple-use-keychain ~/.ssh/personal-github

# Adding your SSH key to your GitHub account
# https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account
printf "run 'pbcopy < ~/.ssh/personal-github.pub' and paste that into GitHub\n"
