#!/usr/bin/env bash

# Define the path to your dotfiles directory
DOTFILES_DIR="$HOME/.dotfiles"

# Check if the ~/.dotfiles directory exists and create it if it doesn't
if [ ! -d "$DOTFILES_DIR" ]; then
    mkdir "$DOTFILES_DIR"
else
    echo "The $DOTFILES_DIR Directory already exists"

fi

# Change to the dotfiles directory
cd "$DOTFILES_DIR" || exit

# Clone the dotfiles repo
git clone git@github.com:LukeAims/.dotfiles.git
# Grab process id of git clone 
clone_pid=$!

# Wait until the git clone operation is finished to ensure all files are available
wait "$clone_pid"

# Run all dotfiles installers.
set -e

cd "$(dirname $0)"/..

# To test the install order without installing anything uncomment this command and comment out the next command
# find . -name 'install-dotfiles'| sort -t- -k2n | while read -r installer; do echo "Installing: $installer"; done

# Run all scripts named install in the current directory and subdirectories 
# (Executes them in order of the directory structure)
find . -name 'install-dotfiles' | sort -t- -k2n | while read -r installer; do sh -c "${installer}"; done
