#!/usr/local/bin/zsh

# shellcheck disable=SC1071

# Enable the option for immediate exit if any command in the script fails.
set -e

##############################################################################################################
# ****                                           Link Dotfiles                                          **** #
##############################################################################################################

########## Variables

# Dotfiles directories
dir=$HOME/.dotfiles  
devdir=$HOME/.dotfiles/development-configuration
gitdir=$HOME//.dotfiles/git
# Old dotfiles backup directory                
olddir=$HOME/dotfiles_old  

# List of files/devfiless to symlink into configdir        
foldersConf="zsh bat neofetch"
# List of files to be symlinked from ~/.dotfiles/development-configuration into homedir
devfiles="eslintrc.js eslintignore prettierrc.json prettierignore editorconfig"
 # List of files/devfiless to symlink into homedir
filesHome="bashrc bash_profile vim vimrc zshenv screenrc inputrc wgetrc curlrc"   

########## Symlinks

# Create dotfiles_old in homedir
echo -n "Creating $olddir for backup of any existing dotfiles in ~ ..."
mkdir -p $olddir
echo "done"

# Change to the dotfiles directory
echo -n "Changing to the $dir directory ..."
cd $dir
echo "done"

# Move any existing dotfiles to dotfiles_old, then create symlinks from the $HOME to the files in our dotfiles directory
for file in $filesHome; do
    echo "Moving any existing dotfiles from ~ to $olddir"
    mv $HOME/.$file $HOME/dotfiles_old/
    echo "Creating symlink to $file in home directory."
    ln -s $dir/$file $HOME/.$file

    echo "Finished processing $file"
done

# Change to the dotfiles directory
echo -n "Changing to the $devdir directory ..."
cd $devdir
echo "done"

for dfile in $devdir; do
     echo "Moving any existing dotfiles from ~ to $olddir"
     mv $HOME/.$dfile $HOME/dotfiles_old/
     echo "Creating symlink to $dfile in ~/.config directory."
     ln -s $devdir/$dfile $HOME/.$dfile

    echo "Finished processing $dfile"
done

for cfile in $foldersConf; do
    echo "Moving any existing dotfiles from ~ to $olddir"
    mv $HOME/.config/$cfile $HOME/dotfiles_old/
    ln -s  $dir/$cfile $HOME/.config/$cfile

    echo "Creating symlink to $cfile in ~/.config directory."
done

# SSH Configuration Files
ln -sfv "$HOME"/.dotfiles/config "$HOME"/.ssh
