#!/usr/bin/env bash

# Check to see what shell we are using then execute the zsh or bash version of the test

if [ -n "$BASH_VERSION" ]; then
  if test ! "$(uname)" = "Darwin"; then
    echo "Shell is bash"
    exit 0
  fi
elif [ -n "$ZSH_VERSION" ]; then
  echo "Shell is Zsh"
  if [[ ! "$(uname)" = "Darwin" ]]; then
    exit 0
  fi
else
  echo "Unsupported shell"
  exit 1
fi

# The Brewfile handles Homebrew-based app and library installs, but there may
# still be updates and installable's in the Mac App Store. So lets check...

echo Running "› macOS softwareupdate"
sudo softwareupdate -i -a

# To test the install without installing anything uncomment this command and comment out the next command
# find . -name 'mac-defaults.sh'| sort -t- -k2n | while read -r installer; do echo "Installing: $installer"; done

find . -name 'mac-defaults' | sort -t- -k2n | while read -r installer; do sh -c "${installer}"; done